language: ruby
cache: bundler
before_install:
- bundle install
- chmod +x ./deploy.sh
script:
- "./deploy.sh"
branches:
  only:
  - master
env:
  global:
    secure: rw9ldfPAF3x41HiZ6/h/qnyfPgclQE/D96oqlk1NiIw0Rvp8nW8/X8cPxdTehDxoezEXRJx/w45jtxN3+c6DIgTLf5kXcOqIGxtYGxU/KVjbG/ZOW/M75OeQKfNhZdIzkLx8FDVBdUK1vD2cExJAy7o8ejUZkm5OsTIri3KKCBfnkCoUzfMsVp2X6kmYk/oDHtwE4PWPctreRYcmkkzq+NxujdPCAmwCsIbjtiQdgmtO2J+uVYoJkmsNooxV5aIG4kZLyFXkCjlJD35BSxWW4eIRJO4jtvP3JYgleeAI+/a9BwYqJmZA+fHAXrs4fq02QoFqGCTBek61yG2EM1S6A780PX150C1BtQnO5xR2vVWQ6D3S2o5yzJ5O4oVospzJovG0j3nVCWItl+eC66x5xfcQN5j/z06n0/qBkYLMQaKyxHYQKn7N0QuKeBWJcUipAJ/NSJuoFEju/POiraCE4GuNTacUn6+qBtQS95pwsaDSY+8u5QvTqnzt1PHQ9yRKhAaLvq1YO3R5NJRpHLiMv7loCwfDCVUItJe/Tv9jfe45b/SzjZSt+Tqjd+lyx8FauI4GjnxINU7k+zf9Dx/0ZFIT8FBVVZ+GwrFKQ5/lu/Ybsjp2yr+KLmxYzRg/Vkmty2Hv5tOPDyAExomZ6ls4DZ+4BYmcG6eCd5lUNdTS1DI=
notifications:
  slack:
    secure: UoVfroICcMJviK4/fSEgqGEUZDhKrrkrURP+B/r9OCQqTNlu35jHOmMez5b1wZnR7kpDfHI2a6QKX6VoNjI/bkdwHDzLArwHmCG91k4X/6xBsZ7vfqCMhQsvWvuN7oSt0V2nPwVWUod7lFuMPZSrmzRsu6KJmFSkawJp6phxmEDRiJVDYU73TiMG8L2xt/hEArTFFhnZdFSMi94z4wgBvUDfwmRXma8NkjnXYCsaa/B02Si2Rsm86enE8cVDmoAkpoWd/+shFzt0gT+bCQ9HH0ZgEIpmEPvV8rKH4ern7Yu8IRL8VD+9xATh73mLOfvKLCeQxdWm1zQUIRD9ibUm+QuH/BTlpshlX1Kxhyn+lewJL+qnlOeEiH0anMWDwibpCufLdNumIY4BwnF8JkjFTZgLtCbZ1NE/HVD7Ioaqd8s3KJUnBo0/BDO4hQIyJbOo8BN0g8qUfM9yazsXTyK6B9tepeQ4y62GeX6leMj+ByIregmY+h29mBmAolbVTWHhfoA4eA7JKIsC+pIT3EXRheeHptnjV8526W6C+kNcz/6svchCzBwIn8U7Spia48XAq6kzFDFGbUbQcSH4iG1nABK37PhfTgORJSDCzZYIBAsElSupQVw9eQ/dd3GPo1Y1Tmf2RA4gJkOAYNgUTJ7SgZmvZsUDZEnCqQKK3yk0M8w=
